;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

;using corecursion discussed in http://en.wikipedia.org/wiki/Corecursion
(def fibonacci (lazy-cat [0 1] (map +' (rest fibonacci) fibonacci)))

;every third number in a fibonacci sequence starting with 0,1,1,.. is EVEN
(reduce + (take-while #(< % 4000000) (take-nth 3 fibonacci)))
;result 4613732

